# Generated by Django 3.2.16 on 2023-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230206_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tip', 'Tip'), ('orig', 'Origin'), ('anec', 'Anecdote'), ('remin', 'Reminiscence'), ('fact', 'Fun Fact'), ('hist', 'History')], default='anec', max_length=5),
        ),
    ]
