# Generated by Django 3.2.16 on 2023-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('fact', 'Fun Fact'), ('orig', 'Origin'), ('anec', 'Anecdote'), ('tip', 'Tip'), ('remin', 'Reminiscence'), ('hist', 'History')], default='anec', max_length=5),
        ),
    ]
