# Generated by Django 3.2.16 on 2023-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('remin', 'Reminiscence'), ('fact', 'Fun Fact'), ('anec', 'Anecdote'), ('tip', 'Tip'), ('orig', 'Origin'), ('hist', 'History')], default='anec', max_length=5),
        ),
    ]
