# Generated by Django 3.2.16 on 2023-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('anec', 'Anecdote'), ('hist', 'History'), ('fact', 'Fun Fact'), ('tip', 'Tip'), ('remin', 'Reminiscence'), ('orig', 'Origin')], default='anec', max_length=5),
        ),
    ]
