# Generated by Django 3.2.16 on 2023-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('remin', 'Reminiscence'), ('orig', 'Origin'), ('tip', 'Tip'), ('fact', 'Fun Fact'), ('anec', 'Anecdote'), ('hist', 'History')], default='anec', max_length=5),
        ),
    ]
