# Generated by Django 3.2.16 on 2023-02-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230207_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('hist', 'History'), ('fact', 'Fun Fact'), ('tip', 'Tip'), ('remin', 'Reminiscence'), ('orig', 'Origin'), ('anec', 'Anecdote')], default='anec', max_length=5),
        ),
    ]
