# Generated by Django 3.2.16 on 2023-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('remin', 'Reminiscence'), ('tip', 'Tip'), ('fact', 'Fun Fact'), ('orig', 'Origin'), ('hist', 'History'), ('anec', 'Anecdote')], default='anec', max_length=5),
        ),
    ]
