# Generated by Django 3.2.16 on 2023-02-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('hist', 'History'), ('fact', 'Fun Fact'), ('orig', 'Origin'), ('remin', 'Reminiscence'), ('anec', 'Anecdote'), ('tip', 'Tip')], default='anec', max_length=5),
        ),
    ]
