# Generated by Django 3.2.16 on 2023-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('orig', 'Origin'), ('tip', 'Tip'), ('hist', 'History'), ('anec', 'Anecdote'), ('fact', 'Fun Fact'), ('remin', 'Reminiscence')], default='anec', max_length=5),
        ),
    ]
