# Generated by Django 3.2.16 on 2023-02-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('remin', 'Reminiscence'), ('tip', 'Tip'), ('anec', 'Anecdote'), ('orig', 'Origin'), ('hist', 'History'), ('fact', 'Fun Fact')], default='anec', max_length=5),
        ),
    ]
