# Generated by Django 3.2.16 on 2023-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('fact', 'Fun Fact'), ('hist', 'History'), ('orig', 'Origin'), ('tip', 'Tip'), ('anec', 'Anecdote'), ('remin', 'Reminiscence')], default='anec', max_length=5),
        ),
    ]
