# Generated by Django 3.2.16 on 2023-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('anec', 'Anecdote'), ('hist', 'History'), ('fact', 'Fun Fact'), ('orig', 'Origin'), ('tip', 'Tip'), ('remin', 'Reminiscence')], default='anec', max_length=5),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
