# Generated by Django 3.2.16 on 2023-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20230212_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('orig', 'Origin'), ('remin', 'Reminiscence'), ('anec', 'Anecdote'), ('hist', 'History'), ('fact', 'Fun Fact'), ('tip', 'Tip')], default='anec', max_length=5),
        ),
    ]
