# Generated by Django 3.2.16 on 2023-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('hist', 'History'), ('anec', 'Anecdote'), ('tip', 'Tip'), ('remin', 'Reminiscence'), ('orig', 'Origin'), ('fact', 'Fun Fact')], default='anec', max_length=5),
        ),
    ]
