# Generated by Django 3.2.16 on 2023-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tip', 'Tip'), ('remin', 'Reminiscence'), ('fact', 'Fun Fact'), ('hist', 'History'), ('orig', 'Origin'), ('anec', 'Anecdote')], default='anec', max_length=5),
        ),
    ]
