# Generated by Django 3.2.16 on 2023-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20230213_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tip', 'Tip'), ('remin', 'Reminiscence'), ('hist', 'History'), ('anec', 'Anecdote'), ('orig', 'Origin'), ('fact', 'Fun Fact')], default='anec', max_length=5),
        ),
    ]
