# Generated by Django 3.2.16 on 2023-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('anec', 'Anecdote'), ('tip', 'Tip'), ('hist', 'History'), ('fact', 'Fun Fact'), ('orig', 'Origin'), ('remin', 'Reminiscence')], default='anec', max_length=5),
        ),
    ]
