# Generated by Django 3.2.16 on 2023-02-02 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('specialty', models.CharField(choices=[('DES', 'Dessert'), ('MEAT', 'Meats'), ('GRILL', 'Grilling'), ('VEG', 'Vegetables'), ('BREAK', 'Breakfast'), ('NO', 'Nothing Really'), ('ALL', 'A little of everything')], default='NO', max_length=5)),
                ('avatar', models.ImageField(default='../default_avatar_kaw1ox', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
