# Generated by Django 3.2.16 on 2023-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230209_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_unit',
            field=models.CharField(choices=[('min', 'min'), ('hr', 'hours')], default='hr', max_length=3),
        ),
    ]
