# Generated by Django 3.2.16 on 2023-02-12 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_alter_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperating',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('owner', 'recipe')},
        ),
    ]
