# Generated by Django 3.2.16 on 2023-02-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230212_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeRating',
        ),
    ]
