# Generated by Django 3.2.16 on 2023-02-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230213_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipelike',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='reciperating',
            options={'ordering': ['-created_on']},
        ),
    ]
